#!/usr/bin/env bash
#
# Repo lint: static checks over this repo's own scripts and data files.
#
#   .github/scripts/lint.sh                      run every check
#   .github/scripts/lint.sh --require-shellcheck fail (instead of skipping) if
#                                                the shellcheck binary is absent
#   .github/scripts/lint.sh --require-append-only fail (instead of skipping) if
#                                                the append-only evidence check
#                                                cannot resolve its base ref
#
# Zero dependencies beyond python3 and (optionally) shellcheck, matching the
# harness's stdlib-only rule -- there is no venv and no package manifest to
# install. Run by `npm run lint` and by the `lint` job in
# .github/workflows/ci.yml, so local and CI results are identical.
#
# Scope: files this repo owns. The vendored `.loom/` and `.claude/` trees and
# the `loom.sh` wrapper are installed and regenerated by external tooling
# (Loom / Repo Skills) -- linting them would gate this repo's PRs on upstream
# code it does not maintain.
#
# Portable to the bash 3.2 that ships with macOS (no mapfile/readarray).
#
# Exit codes: 0 pass, 1 a check failed.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}" || exit 1

REQUIRE_SHELLCHECK=0
EVIDENCE_ARGS=()
for arg in "$@"; do
  case "${arg}" in
    --require-shellcheck) REQUIRE_SHELLCHECK=1 ;;
    --require-append-only) EVIDENCE_ARGS+=(--require-append-only) ;;
    -h|--help) sed -n '2,24p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: ${arg}" >&2; exit 1 ;;
  esac
done

status=0

# Tracked, repo-owned files matching one glob, collected into the `files`
# array. Tracked-only, so generated/ignored artefacts are never linted; the
# vendored .loom/ and .claude/ trees are excluded (see the header).
collect() {
  files=()
  while IFS= read -r -d '' path; do
    files+=("${path}")
  done < <(git ls-files -z -- "$1" ':!:.loom/**' ':!:.claude/**' ':!:loom.sh')
}

echo "== 1/5 shellcheck (shell scripts) =="
collect '*.sh'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no shell scripts tracked"
elif command -v shellcheck >/dev/null 2>&1; then
  printf '%s\n' "${files[@]}"
  if ! shellcheck "${files[@]}"; then
    echo "FAIL: shellcheck"
    status=1
  fi
elif [ "${REQUIRE_SHELLCHECK}" -eq 1 ]; then
  echo "FAIL: shellcheck is not installed (--require-shellcheck)"
  status=1
else
  echo "SKIP: shellcheck is not installed (brew install shellcheck / apt-get install shellcheck)"
fi

echo
echo "== 2/5 python syntax =="
collect '*.py'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no python files tracked"
else
  printf '%s\n' "${files[@]}"
  # A syntax error anywhere in the harness or in a testbench runner fails here
  # instead of halfway through a simulation run.
  if ! python3 -m compileall -q "${files[@]}"; then
    echo "FAIL: python syntax"
    status=1
  fi
fi

echo
echo "== 3/5 json well-formedness =="
collect '*.json'
if [ "${#files[@]}" -eq 0 ]; then
  echo "no json files tracked"
else
  printf '%s\n' "${files[@]}"
  # Testbench manifests (sim/<slug>/testbench/tb.json), sim/pdk.json and
  # package.json are all hand-edited; a stray comma should not reach a
  # simulation run.
  if ! python3 -c '
import json
import sys

bad = 0
for path in sys.argv[1:]:
    try:
        with open(path, encoding="utf-8") as handle:
            json.load(handle)
    except (OSError, ValueError) as exc:
        print(f"{path}: {exc}")
        bad += 1
sys.exit(1 if bad else 0)
' "${files[@]}"; then
    echo "FAIL: malformed json"
    status=1
  fi
fi

echo
echo "== 4/5 evidence records (sim/*/records) =="
# The schema in sim/README.md -- nine required fields, <record-id> naming, the
# corner-id grammar, and the append-only rule -- enforced instead of merely
# documented. Tracked files only, same as collect() above; the append-only half
# diffs against the merge base with origin/main and SKIPs (unless
# --require-append-only) where that ref does not resolve.
if ! python3 sim/check_records.py ${EVIDENCE_ARGS[@]+"${EVIDENCE_ARGS[@]}"}; then
  echo "FAIL: evidence records"
  status=1
fi

echo
echo "== 5/5 DUT freshness (sim/dut/bandgap_top.spice) =="
# sim/dut/bandgap_top.spice is generated from design/netlist/bandgap_top.spice
# (sim/dut/README.md) and every spec-line bench simulates it via each tb.json's
# "dut" key. Nothing else re-derives it, so a schematic edit that lands
# without regenerating this fragment is invisible until this check: the suite
# would otherwise keep minting records -- silently -- against a netlist the
# repo no longer contains (#51). Only runs when both files are tracked, so a
# worktree missing either (e.g. a sparse checkout) SKIPs instead of failing.
if [ -f design/netlist/bandgap_top.spice ] && [ -f sim/dut/bandgap_top.spice ]; then
  if ! python3 sim/tools/mk_dut.py design/netlist/bandgap_top.spice sim/dut/bandgap_top.spice --check; then
    echo "FAIL: sim/dut/bandgap_top.spice is stale -- regenerate with:"
    echo "  python3 sim/tools/mk_dut.py design/netlist/bandgap_top.spice sim/dut/bandgap_top.spice"
    status=1
  fi
else
  echo "SKIP: design/netlist/bandgap_top.spice or sim/dut/bandgap_top.spice not present"
fi

echo
if [ "${status}" -eq 0 ]; then
  echo "PASS: lint clean."
else
  echo "FAIL: lint found problems."
fi
exit "${status}"
