#!/usr/bin/env python3
"""Pure-generator checks for mk_klt_request and measure_lumped_r1 (issue #251).

No PDK, ngspice, network or fleet required.
"""

from __future__ import annotations

import contextlib
import io
import re
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SIM = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SIM))
sys.path.insert(0, str(SIM / "tools"))

import measure_lumped_r1 as lr  # noqa: E402
import mk_klt_request as mk  # noqa: E402


class CurveMeas(unittest.TestCase):
    def _check(self, cards, temps):
        self.assertEqual(len(cards), len(temps))
        names = [c[0] for c in cards]
        self.assertEqual(len(names), len(set(names)))
        for (name, card, unit), t in zip(cards, temps):
            self.assertEqual(name, f"vref_t{t}".replace("-", "m"))
            self.assertEqual(unit, "V")
            self.assertEqual(card, f".meas dc {name} FIND v(vref) AT={t}")

    def test_default_step(self):
        temps = list(range(-40, 126, mk.CURVE_STEP_C))
        self._check(mk.curve_meas(), temps)
        self.assertEqual(temps[0], -40)
        self.assertEqual(temps[-1], 125)

    def test_custom_step(self):
        # 165 is not a multiple of 50: last sample stays inside the range
        self._check(mk.curve_meas(50), [-40, 10, 60, 110])


class Inline(unittest.TestCase):
    def setUp(self):
        self._td = tempfile.TemporaryDirectory()
        self.addCleanup(self._td.cleanup)
        d = Path(self._td.name)
        self.a = d / "a.inc"
        self.b = d / "b.spice"
        self.c = d / "c.spice"
        self.a.write_text("* A\n.model x\n")
        self.b.write_text("* B1\n.end\n* B2\n.ends\n\n")
        self.c.write_text("* C\n.end\n")

    def test_inline_parts_order_and_contents(self):
        out = mk.inline_parts("lbl", (("one", self.a), ("two", self.b)), generator="gen.py")
        self.assertEqual(out[0], "* lbl -- GENERATED by gen.py, do not edit")
        self.assertEqual(out[1], "* ---- begin inlined one: a.inc ----")
        self.assertEqual(out[2], "* A\n.model x")
        self.assertEqual(out[3], "* ---- end inlined one ----")
        self.assertEqual(out[4], "* ---- begin inlined two: b.spice ----")
        self.assertEqual(out[6], "* ---- end inlined two ----")
        self.assertEqual(len(out), 7)

    def test_interior_end_removed(self):
        text = "\n".join(mk.inline_parts("l", (("two", self.b),)))
        self.assertNotIn("\n.end\n", text)
        self.assertIn("* B1\n* B2\n.ends", text)

    def test_trailing_end_kept_per_existing_contract(self):
        # only an interior ".end" line is stripped; a final one has no trailing newline
        out = mk.inline_parts("l", (("c", self.c),))
        self.assertEqual(out[2], "* C\n.end")

    def test_inline_netlist_order(self):
        out = mk.inline_netlist(self.b, self.c, self.a, "bench")
        begins = [l for l in out if l.startswith("* ---- begin")]
        self.assertEqual(
            begins,
            [
                "* ---- begin inlined design.ngspice (PDK): a.inc ----",
                "* ---- begin inlined DUT: b.spice ----",
                "* ---- begin inlined testbench: c.spice ----",
            ],
        )
        self.assertIn("mk_klt_request.py", out[0])


TRIM = ".subckt bandgap_trim a b sub\nXRU0 a b sub ppolyf_u r_width=2u r_length=7u m=1\n.ends bandgap_trim"
TOP_TEXT = f"* top\nXR1 e3 tn0 vss ppolyf_u r_width=2u r_length=12.5u m=1\n{TRIM}\n.end\n"


class LumpedR1(unittest.TestCase):
    def setUp(self):
        self._td = tempfile.TemporaryDirectory()
        self.addCleanup(self._td.cleanup)
        self.top = Path(self._td.name) / "top.spice"
        self.top.write_text(TOP_TEXT)
        p = mock.patch.object(lr, "TOP", self.top)
        p.start()
        self.addCleanup(p.stop)

    def test_trim_subckt_extracted(self):
        self.assertEqual(lr.trim_subckt(), TRIM)

    def test_trim_subckt_missing(self):
        self.top.write_text("* nothing here\n.end\n")
        with self.assertRaises(SystemExit):
            lr.trim_subckt()

    def test_base_length(self):
        self.assertEqual(lr.base_r1_length(), "12.5u")

    def test_deck_wiring(self):
        d = lr.deck("/p/design.ngspice", "/p/sm.ngspice", "res_typical", ["500.0", "600.5"], "12.5u")
        lines = d.splitlines()
        self.assertIn(".include /p/design.ngspice", lines)
        self.assertIn(".lib /p/sm.ngspice res_typical", lines)
        self.assertIn(TRIM, d)
        self.assertIn("vsub sub 0 0", lines)
        # one reference base resistor + trim ladder
        self.assertEqual(len([l for l in lines if l.startswith("XR1ref ")]), 1)
        self.assertIn("XR1ref atop tn0 sub ppolyf_u r_width=2u r_length=12.5u m=1", lines)
        self.assertIn("XXTRIM tn0 abot sub bandgap_trim", lines)
        self.assertIn("vtop atop 0 0.05", lines)
        self.assertIn("vbot abot 0 0", lines)
        # per lumped branch: substrate-tied device, distinct top/bottom sources
        for i, ln in enumerate(["500.0", "600.5"]):
            self.assertIn(f"XRL{i} ltop{i} lbot{i} sub ppolyf_u r_width=2u r_length={ln}u m=1", lines)
            self.assertIn(f"vltop{i} ltop{i} 0 0.05", lines)
            self.assertIn(f"vlbot{i} lbot{i} 0 0", lines)
        self.assertEqual(len([l for l in lines if l.startswith("XRL")]), 2)
        srcs = [l.split()[0] for l in lines if re.match(r"v\w+ ", l)]
        self.assertEqual(len(srcs), len(set(srcs)))
        self.assertEqual(len(srcs), 2 + 1 + 4)  # vsub, vtop/vbot, 2x(top,bot)

    def test_control(self):
        temps = (-40.0, 125.0)
        biases = (("lowbias", 0.0, 0.05), ("opbias", 0.7, 0.5))
        lines = lr.control(2, temps, biases).splitlines()
        self.assertEqual(lines[0], ".control")
        self.assertEqual(lines.count("op"), 4)
        self.assertEqual(len([l for l in lines if l.startswith("echo PT")]), 4)
        for tok in ("quit", ".endc", ".end"):
            self.assertEqual(lines.count(tok), 1, tok)
        self.assertEqual(lines[-3:], ["quit", ".endc", ".end"])
        self.assertFalse([l for l in lines if l.startswith((".step", ".meas"))])
        # walk each op block in order: temp/bias pairs
        pairs = [(t, b) for t in temps for b in biases]
        idx = [i for i, l in enumerate(lines) if l == "op"]
        start = 0
        for (t, (label, vbot, vdrop)), oi in zip(pairs, idx):
            blk = lines[start:oi]
            self.assertIn(f"option temp={t}", blk)
            self.assertIn(f"alter vbot dc = {vbot}", blk)
            self.assertIn(f"alter vtop dc = {vbot + vdrop}", blk)
            for i in range(2):
                self.assertIn(f"alter vlbot{i} dc = {vbot}", blk)
                self.assertIn(f"alter vltop{i} dc = {vbot + vdrop}", blk)
            echo = lines[oi + 1]
            self.assertEqual(
                echo, f"echo PT {t} {label} {vdrop} ref $&i(vtop) L0 $&i(vltop0) L1 $&i(vltop1)"
            )
            start = oi + 2

    def test_check_length_nonnumeric_rejected_before_pdk(self):
        with mock.patch.object(lr, "pdk_paths", side_effect=AssertionError("PDK accessed")), \
             mock.patch.object(lr, "run", side_effect=AssertionError("ngspice accessed")), \
             mock.patch.object(sys, "argv", ["measure_lumped_r1.py", "--check-length", "abc"]), \
             contextlib.redirect_stderr(io.StringIO()):
            with self.assertRaises(SystemExit) as cm:
                lr.main()
        self.assertEqual(cm.exception.code, 2)


if __name__ == "__main__":
    unittest.main()
