#!/usr/bin/env python3
"""Emit a `klt sim` request for the equal-Ie Q2 array device bench (#208).

`mk_klt_request.py` only knows the circuit-level benches (`output-voltage-tc`,
`iq`) and derives its corner list from a `tb.json`. The device-level array
experiment has no supply rail and no `tb.json` (it is not a generic-harness
bench), so it gets this focused adapter instead. Everything the request
contains is built by pure functions here so the unit checks in
`sim/tests/test_pnp_array.py` can pin it down without a PDK or a fleet.

    python3 sim/tools/mk_klt_device_request.py OUTDIR
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM = HERE.parent
REPO = SIM.parent
sys.path.insert(0, str(SIM))

BENCH_DIR = SIM / "device-pnp-array" / "testbench"
BENCH = "tb_pnp_array.spice"

# gf180mcu has no global switch: the BJT process corners are model `.lib`
# sections of their own (see sim/harness/corners.py).
BJT_SECTIONS = ("bjt_ss", "bjt_typical", "bjt_ff")
# CLAUDE.md PVT axis. klt takes degrees Celsius (and writes `.temp <C>`).
TEMPS_C = (-40.0, 27.0, 125.0)
# Emitter currents (uA) reported: the design current I = dVBE/R2 (DR-0007
# item 1), the historical 6.5 uA point of #87's Finding, and a low point.
DESIGN_UA = 5.07
HISTORICAL_UA = 6.5
CURRENTS_UA = (4.0, DESIGN_UA, HISTORICAL_UA)
SWEEP = "Vctrl 4.0 7.0 0.01"
# one-unit, four-unit-array and monolithic-10x10 branch nodes
BRANCHES = {"u": "eu", "a": "ea", "m": "em"}


def tag(ua: float) -> str:
    """Measurement-name token for a current in uA: 5.07 -> '5p07'."""
    return f"{ua:g}".replace(".", "p")


def meas_name(branch: str, ua: float) -> str:
    return f"vbe_{branch}_{tag(ua)}"


def measurements() -> list[dict]:
    """Raw `.meas` cards (not `expr`: the fleet's pinned klt can lag)."""
    out = []
    for ua in CURRENTS_UA:
        for branch, node in BRANCHES.items():
            name = meas_name(branch, ua)
            out.append(
                {"name": name, "spice": f".meas dc {name} FIND v({node}) AT={ua:g}", "unit": "V"}
            )
    return out


def build_request(sections=BJT_SECTIONS, temps_c=TEMPS_C) -> dict:
    sections, temps_c = list(sections), list(temps_c)
    if not sections or not temps_c:
        raise ValueError("process and temperature axes must be non-empty")
    return {
        "netlist": "body.spice",
        "engine": "ngspice",
        "models": {"pdk": "gf180mcuD", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": s, "sections": [s]} for s in sections],
            "temperature_c": temps_c,
        },
        "analysis": {"kind": "dc", "args": SWEEP},
        "measurements": measurements(),
        "options": {"timeout_s": 300, "keep_artifacts": True},
    }


def body_lines(bench_path: Path) -> list[str]:
    return [
        "* device-pnp-array -- GENERATED by sim/tools/mk_klt_device_request.py, do not edit",
        # Copy of the PDK's design.ngspice staged with the request: the fleet
        # klt does not expand $PDK_ROOT in the netlist.
        '.include "design.ngspice"',
        f'.include "{bench_path}"',
        "",
    ]


def expected_points(sections=BJT_SECTIONS, temps_c=TEMPS_C) -> list[tuple[str, float]]:
    return [(s, t) for s in sections for t in temps_c]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    a = ap.parse_args()
    from harness import pdk as hp

    out = Path(a.outdir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    (out / "design.ngspice").write_text(hp.find_pdk().design_include.read_text())
    (out / "body.spice").write_text("\n".join(body_lines(BENCH_DIR / BENCH)))
    (out / "request.json").write_text(json.dumps(build_request(), indent=2) + "\n")
    print(f"wrote {out}/request.json ({len(BJT_SECTIONS)} x {len(TEMPS_C)} points)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
