#!/usr/bin/env python3
"""Emit a `klt sim` request for one single-analysis harness bench.

Why this exists: the repo's own corner runner (`sim/run_corners.py`) fans
ngspice out from the invoking host. Shared dispatch workers must not run
SPICE grids themselves; they express the grid as a `klt sim` request and let
`KLT_SIM_BACKEND=batch` send it to the Spot fleet. This script derives such a
request *from the bench's own tb.json and `sim/harness/corners.py`*, so the
corner list, supply points, DUT and measurement expressions are the
harness's, not a second hand-maintained copy.

Scope: benches whose analysis is one card (`op`, or one `dc temp ...` sweep).
Every bench becomes one `dc temp` sweep (`iq` a degenerate 27..27 one): the
outer temperature axis is dropped (corner `.temp` fixed at 27 C) and the
quantities at -40/27/125 C are read from the sweep -- the same numbers
`sim/run_suite.py` cross-checks against the outer-axis op points.

    python3 sim/tools/mk_klt_request.py output-voltage-tc [--dut PATH] OUTDIR
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM = HERE.parent
REPO = SIM.parent
sys.path.insert(0, str(SIM))

from harness import corners as hc  # noqa: E402

# bench -> (klt analysis, [(name, .meas card, unit)]).
# `.meas` cards, not `measurements[].expr`: the batch fleet's pinned klt image
# can lag the submitting klt and rejects `expr` entries only after a Spot boot.
# Derived quantities (tc_ppm, iq_ua) and the verdicts are computed by
# sim/tools/klt_summarize.py from these raw measurements.
BENCH = {
    "output-voltage-tc": (
        {"kind": "dc", "args": "temp -40 125 1"},
        [
            ("vref_m40", ".meas dc vref_m40 FIND v(vref) AT=-40", "V"),
            ("vref_27", ".meas dc vref_27 FIND v(vref) AT=27", "V"),
            ("vref_125", ".meas dc vref_125 FIND v(vref) AT=125", "V"),
            ("vref_box_max", ".meas dc vref_box_max MAX v(vref)", "V"),
            ("vref_box_min", ".meas dc vref_box_min MIN v(vref)", "V"),
        ],
    ),
    "iq": (
        {"kind": "dc", "args": "temp 27 27 1"},
        [
            ("isup", ".meas dc isup FIND i(vsup) AT=27", "A"),
            ("vref", ".meas dc vref FIND v(vref) AT=27", "V"),
        ],
    ),
}


def hc_pdk():
    from harness import pdk as hp

    return hp.find_pdk()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("bench", choices=sorted(BENCH))
    ap.add_argument("outdir")
    ap.add_argument("--dut", default="sim/dut/bandgap_top.spice")
    a = ap.parse_args()

    tb = json.loads((SIM / a.bench / "testbench" / "tb.json").read_text())
    out = Path(a.outdir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    rel = lambda p: str(Path(p).resolve().relative_to(REPO))  # noqa: E731

    body = [
        f"* {a.bench} -- GENERATED by sim/tools/mk_klt_request.py, do not edit",
        f".param vdd_nom={tb['nominal_supply_v']!r}",
        f".param vdd_val={tb['nominal_supply_v']!r}",
        ".param temp_c=27.0",
        # A *copy* of the PDK's design.ngspice, staged with the request: the
        # fleet's klt does not expand `$PDK_ROOT` inside the netlist, so the
        # verbatim env-var include silently resolves to nothing there.
        '.include "design.ngspice"',
        f'.include "{REPO / a.dut}"',
        f'.include "{SIM / a.bench / "testbench" / tb["netlist"]}"',
        "",
    ]
    (out / "design.ngspice").write_text((hc_pdk().design_include).read_text())
    (out / "body.spice").write_text("\n".join(body))

    names = tb["corners"]
    corners = hc.resolve_corners(names)
    process = [{"name": c.name, "sections": list(c.sections)} for c in corners]
    vdds = hc.supply_points(tb["nominal_supply_v"], tb.get("supply_tolerance", 0.0))
    analysis, meas = BENCH[a.bench]
    req = {
        "netlist": "body.spice",
        "engine": "ngspice",
        "models": {"pdk": "gf180mcuD", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": process,
            "supply_v": {"vdd_val": vdds},
            "temperature_c": [27],
        },
        "analysis": analysis,
        "measurements": [],
        "options": {"timeout_s": 300, "keep_artifacts": True},
    }
    for name, card, unit in meas:
        req["measurements"].append({"name": name, "spice": card, "unit": unit})
    (out / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    print(f"wrote {out}/request.json ({len(corners)} corners x {len(vdds)} supply)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
