#!/usr/bin/env python3
"""Emit a `klt sim` request for one single-analysis harness bench.

Why this exists: the repo's own corner runner (`sim/run_corners.py`) fans
ngspice out from the invoking host. Shared dispatch workers must not run
SPICE grids themselves; they express the grid as a `klt sim` request and let
`KLT_SIM_BACKEND=batch` send it to the Spot fleet. This script derives such a
request *from the bench's own tb.json and `sim/harness/corners.py`*, so the
corner list, supply points, DUT and measurement expressions are the
harness's, not a second hand-maintained copy.

Scope: benches whose analysis is one card (`op`, or one `dc temp ...` sweep).
Every bench becomes one `dc temp` sweep (`iq` a degenerate 27..27 one): the
outer temperature axis is dropped (corner `.temp` fixed at 27 C) and the
quantities at -40/27/125 C are read from the sweep -- the same numbers
`sim/run_suite.py` cross-checks against the outer-axis op points.

    python3 sim/tools/mk_klt_request.py output-voltage-tc [--dut PATH] OUTDIR
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM = HERE.parent
REPO = SIM.parent
sys.path.insert(0, str(SIM))

from harness import corners as hc  # noqa: E402

# bench -> (klt analysis, [(name, .meas card, unit)]).
# `.meas` cards, not `measurements[].expr`: the batch fleet's pinned klt image
# can lag the submitting klt and rejects `expr` entries only after a Spot boot.
# Derived quantities (tc_ppm, iq_ua) and the verdicts are computed by
# sim/tools/tc_ingest.py from these raw measurements.
BENCH = {
    "output-voltage-tc": (
        {"kind": "dc", "args": "temp -40 125 1"},
        [
            ("vref_m40", ".meas dc vref_m40 FIND v(vref) AT=-40", "V"),
            ("vref_27", ".meas dc vref_27 FIND v(vref) AT=27", "V"),
            ("vref_125", ".meas dc vref_125 FIND v(vref) AT=125", "V"),
            ("vref_box_max", ".meas dc vref_box_max MAX v(vref)", "V"),
            ("vref_box_min", ".meas dc vref_box_min MIN v(vref)", "V"),
        ],
    ),
    "iq": (
        {"kind": "dc", "args": "temp 27 27 1"},
        [
            ("isup", ".meas dc isup FIND i(vsup) AT=27", "A"),
            ("vref", ".meas dc vref FIND v(vref) AT=27", "V"),
        ],
    ),
}


# klt `alter`s this *device* per supply point: it is the bench's `vsup vdd 0 dc {vdd_val}`
# source (an `alter vdd_val=` on the .param name matches no device and errors).
SUPPLY_SOURCE = "vsup"
CURVE_STEP_C = 5  # sampled Vref(T) points for retuning (output-voltage-tc only)


def curve_meas(step: int = CURVE_STEP_C):
    """Extra `.meas` cards sampling Vref(T) every `step` C over -40..125 C.

    Not part of the verdict (the box extrema come from the 1 C sweep itself);
    they make Vref(T) reconstructable per corner so R1 can be re-nulled from
    two runs by exact affine interpolation (Vref is affine in R1).
    """
    temps = list(range(-40, 126, step))
    return [
        (f"vref_t{t}".replace("-", "m"), f".meas dc vref_t{t}".replace("-", "m") + f" FIND v(vref) AT={t}", "V")
        for t in temps
    ]


def inline_parts(label: str, parts, generator: str = "sim/tools/mk_klt_request.py") -> list[str]:
    """One self-contained deck from ``[(title, path), ...]``: the fleet stages
    only the request's netlist file, so `.include`s are inlined here."""
    out = [f"* {label} -- GENERATED by {generator}, do not edit"]
    for title, path in parts:
        out += [f"* ---- begin inlined {title}: {path.name} ----", path.read_text().rstrip().replace("\n.end\n", "\n"), f"* ---- end inlined {title} ----"]
    return out


def inline_netlist(a_dut: Path, tb_path: Path, design_include: Path, label: str) -> list[str]:
    """PDK design.ngspice + DUT + testbench (see :func:`inline_parts`)."""
    return inline_parts(label, (("design.ngspice (PDK)", design_include), ("DUT", a_dut), ("testbench", tb_path)))


def hc_pdk():
    from harness import pdk as hp

    return hp.find_pdk()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("bench", choices=sorted(BENCH))
    ap.add_argument("outdir")
    ap.add_argument("--dut", default="sim/dut/bandgap_top.spice")
    ap.add_argument("--curve", action="store_true", help="add Vref(T) sample points every 5 C (retuning aid)")
    a = ap.parse_args()

    tb = json.loads((SIM / a.bench / "testbench" / "tb.json").read_text())
    out = Path(a.outdir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    rel = lambda p: str(Path(p).resolve().relative_to(REPO))  # noqa: E731

    dut = (REPO / a.dut).resolve()
    design_inc = hc_pdk().design_include
    head = [
        f".param vdd_nom={tb['nominal_supply_v']!r}",
        f".param vdd_val={tb['nominal_supply_v']!r}",
        ".param temp_c=27.0",
        # gf180mcu's BSIM4 bins are per finger. ngspice only divides the
        # instance W by nf for bin selection when wnflag=1 (inpgmod.c); the
        # default (hspice/spectre-off) bins on the total W and fails
        # "could not find a valid modelname" for W=300u nf=12 on ngspice
        # 42..47. Set explicitly so the fleet (ngspice 46) agrees with a
        # workstation whose ~/.spiceinit may already set it.
        ".options wnflag=1",
    ]
    deck = inline_netlist(dut, SIM / a.bench / "testbench" / tb["netlist"], design_inc, a.bench)
    body = [deck[0]] + head + deck[1:] + [""]
    (out / "body.spice").write_text("\n".join(body))

    names = tb["corners"]
    corners = hc.resolve_corners(names)
    process = [{"name": c.name, "sections": list(c.sections)} for c in corners]
    vdds = hc.supply_points(tb["nominal_supply_v"], tb.get("supply_tolerance", 0.0))
    analysis, meas = BENCH[a.bench]
    meas = list(meas) + (curve_meas() if a.curve and a.bench == "output-voltage-tc" else [])
    req = {
        "netlist": "body.spice",
        "engine": "ngspice",
        "models": {"pdk": "gf180mcuD", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": process,
            "supply_v": {SUPPLY_SOURCE: vdds},
            "temperature_c": [27],
        },
        "analysis": analysis,
        "measurements": [],
        "options": {"timeout_s": 300, "keep_artifacts": True},
    }
    for name, card, unit in meas:
        req["measurements"].append({"name": name, "spice": card, "unit": unit})
    (out / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    print(f"wrote {out}/request.json ({len(corners)} corners x {len(vdds)} supply)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
