"""Deck composition and ngspice execution for one PVT point."""

from __future__ import annotations

import math
import re
import shutil
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

from .corners import PvtPoint
from .pdk import Pdk
from .testbench import Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 300

# `print` output for a length-1 vector: "m_vout = 6.9043645202e-01"
_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")
#: A simulator error diagnostic. Anchored at the start of a line so ngspice's
#: benign chatter -- ``Warning: Dynamic gmin stepping failed`` (a warning: the
#: solver falls back to source stepping and converges), ``Note: ...`` -- does
#: not match. Checked against every committed ``sim/*/corners/**/*.log``: none
#: of the accepted evidence logs carries a line this pattern matches.
_ERROR_RE = re.compile(
    r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:|run simulation\(s\) aborted)",
    re.MULTILINE,
)

#: First line of the trailer :func:`run_point` appends to the raw log of any
#: point it did not accept (``status != "ok"``), *after* ngspice's own output,
#: which is preserved verbatim above it. Downstream readers of the raw logs
#: (``sim/suite/analysis.py``) key on this so an invalid point's numbers can
#: never feed a PASS verdict. Keep in sync with ``suite.analysis``.
INVALID_POINT_MARKER = "*** sim/harness: INVALID POINT"


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  macOS:  brew install ngspice\n"
            "  Debian: apt-get install ngspice"
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


def compose_deck(tb: Testbench, pdk: Pdk, point: PvtPoint) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point."""
    lines: list[str] = [
        f"* {tb.name} @ {point.corner_id} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  pdk={pdk.variant}@{pdk.version}",
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
    ]
    for key, value in tb.params.items():
        lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
        f'.include "{pdk.design_include}"',
    ]
    for section in point.corner.sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')

    lines += [
        "",
        f".temp {point.temp_c!r}",
    ]
    for option in tb.options:
        lines.append(f".options {option}")

    if tb.dut is not None:
        lines += [
            "",
            "* ---- device under test ----------------------------------------------",
            f"* provenance: {tb.dut_provenance_class}  sha256 {tb.dut_sha256}",
            f'.include "{tb.dut}"',
        ]

    lines += [
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{tb.netlist}"',
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    lines += [f"  {analysis}" for analysis in tb.analyses]
    for name, expr in tb.measure.items():
        lines.append(f"  let m_{name} = {expr}")
    for name in tb.measure:
        lines.append(f"  print m_{name}")
    # Explicit successful termination (see run_point's termination policy):
    # with `quit` as the last control command, a deck that ran to completion
    # exits 0, so any other exit status means ngspice never got here.
    lines += ["  quit", ".endc", ".end", ""]
    return "\n".join(lines)


@dataclass
class PointResult:
    """Outcome of one PVT point.

    ``status`` is the *simulation-validity* verdict, kept separate from the
    spec-limit verdict (``report.evaluate_checks``, which only ever looks at
    ``ok`` points):

    - ``"ok"``     -- ngspice exited 0, printed no error diagnostic, and every
      requested measurement parsed. The only status whose numbers count.
    - ``"failed"`` -- ngspice ran to an exit but the run is not valid evidence:
      a non-zero exit, an error diagnostic in the log, or a missing
      measurement. Any measurements that did parse are kept for investigation.
    - ``"error"``  -- the process did not terminate normally: timeout, or
      killed by a signal.
    """

    point: PvtPoint
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    seconds: float = 0.0
    deck: str = ""
    log: str = ""
    message: str = ""
    returncode: int | None = None                 # None: no exit status (timeout)
    diagnostic: str = ""                          # first simulator error line, if any

    def as_dict(self) -> dict:
        record = self.point.as_dict()
        record.update(
            {
                "status": self.status,
                "measurements": self.measurements,
                "seconds": round(self.seconds, 3),
                "deck": self.deck,
                "log": self.log,
                "returncode": self.returncode,
            }
        )
        if self.missing:
            record["missing_measurements"] = self.missing
        if self.diagnostic:
            record["diagnostic"] = self.diagnostic
        if self.message:
            record["message"] = self.message
        return record


def _scan_measurements(text: str) -> tuple[dict[str, float], dict[str, str]]:
    """Split ``m_<name> = <scalar>`` lines into finite values and non-finite text."""
    found: dict[str, float] = {}
    nonfinite: dict[str, str] = {}
    for line in text.splitlines():
        match = _MEAS_RE.match(line)
        if match:
            try:
                value = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
            name = match.group(1)
            if math.isfinite(value):
                found[name] = value
                nonfinite.pop(name, None)
            else:
                # Text such as ``1e999`` overflows to inf; never evidence.
                found.pop(name, None)
                nonfinite[name] = match.group(2)
    return found, nonfinite


def parse_measurements(text: str) -> dict[str, float]:
    """Finite ``m_<name>`` scalars only; overflowed/inf/nan values are dropped."""
    return _scan_measurements(text)[0]


def first_diagnostic(text: str) -> str:
    """The first simulator error line in ``text``, stripped, or ``""``."""
    for line in text.splitlines():
        if _ERROR_RE.match(line):
            return line.strip()
    return ""


def classify_point(
    output: str,
    returncode: int,
    measure_names: list[str],
) -> tuple[str, dict[str, float], list[str], str, str]:
    """Apply the termination/diagnostic policy to one finished ngspice run.

    Returns ``(status, measurements, missing, diagnostic, message)``. Every
    rule is independent of whether the measurements parsed: numbers printed
    before (or despite) a simulator error are not evidence.
    """
    measurements, nonfinite = _scan_measurements(output)
    missing = [name for name in measure_names if name not in measurements]
    diagnostic = first_diagnostic(output)

    if returncode < 0:
        reason = f"ngspice terminated by signal {-returncode}"
        return "error", measurements, missing, diagnostic, (
            f"{reason}: {diagnostic}" if diagnostic else reason
        )

    reasons: list[str] = []
    if diagnostic:
        reasons.append(f"simulator error: {diagnostic}")
    if returncode != 0:
        reasons.append(f"ngspice exit {returncode}")
    absent = [name for name in missing if name not in nonfinite]
    if absent:
        reasons.append("missing " + ", ".join(f"m_{name}" for name in absent))
    bad = [name for name in measure_names if name in nonfinite]
    if bad:
        reasons.append(
            "non-finite "
            + ", ".join(f"m_{name} = {nonfinite[name]}" for name in bad)
        )
    if not reasons:
        return "ok", measurements, missing, diagnostic, ""
    return "failed", measurements, missing, diagnostic, "; ".join(reasons)


def _invalid_trailer(status: str, message: str, returncode: int | None) -> str:
    exit_text = "none (no exit status)" if returncode is None else str(returncode)
    return (
        f"\n{INVALID_POINT_MARKER} -- status={status} ***\n"
        f"*** exit status: {exit_text}\n"
        f"*** reason: {message}\n"
    )


def _as_text(data) -> str:
    if data is None:
        return ""
    if isinstance(data, bytes):
        return data.decode(errors="replace")
    return data


def run_point(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    log_dir: Path | None = None,
) -> PointResult:
    """Simulate one PVT point. Never raises for simulation failure.

    ``workdir`` holds the generated deck (scratch, disposable). ``log_dir``
    -- when given -- is where the raw ngspice output lands as
    ``<corner-id>.log``; that is the ``sim/<slug>/corners/<record-id>/``
    directory from ``sim/README.md``. It defaults to ``workdir`` so a
    throwaway run does not touch the evidence tree.

    Termination policy (ngspice batch mode, ``ngspice -b``; documented in
    ``sim/harness/README.md``): the generated control block ends in an
    explicit ``quit``, so a run that reaches the end of its analyses exits 0.
    A point is ``ok`` only if **all** of these hold -- the exit status is 0,
    the log carries no simulator error diagnostic, and every requested
    measurement parsed. A timeout or a signal-terminated process is
    ``error``; anything else short of ``ok`` is ``failed``. The raw log is
    always written, with any parsed measurements and the first diagnostic
    kept on the result; a non-``ok`` point's log gets a harness trailer
    (``INVALID_POINT_MARKER``) appended after ngspice's own output.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    log_dir = workdir if log_dir is None else log_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    deck_path = workdir / f"{point.corner_id}.spice"
    log_path = log_dir / f"{point.corner_id}.log"
    deck_path.write_text(compose_deck(tb, pdk, point))

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=workdir,
            check=False,
        )
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - started
        partial = _as_text(exc.stdout) + "\n" + _as_text(exc.stderr)
        measurements = parse_measurements(partial)
        diagnostic = first_diagnostic(partial)
        message = f"ngspice timed out after {timeout_s}s"
        log_path.write_text(
            partial
            + f"\nTIMEOUT after {timeout_s}s\n"
            + _invalid_trailer("error", message, None)
        )
        return PointResult(
            point=point,
            status="error",
            measurements=measurements,
            missing=[name for name in tb.measure if name not in measurements],
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=message,
            returncode=None,
            diagnostic=diagnostic,
        )
    elapsed = time.monotonic() - started
    output = proc.stdout + "\n" + proc.stderr

    status, measurements, missing, diagnostic, message = classify_point(
        output, proc.returncode, list(tb.measure)
    )
    if status != "ok":
        output += _invalid_trailer(status, message, proc.returncode)
    log_path.write_text(output)

    return PointResult(
        point=point,
        status=status,
        measurements=measurements,
        missing=missing,
        seconds=elapsed,
        deck=deck_path.name,
        log=log_path.name,
        message=message,
        returncode=proc.returncode,
        diagnostic=diagnostic,
    )


def run_grid(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    jobs: int = 1,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    on_result=None,
    log_dir: Path | None = None,
) -> list[PointResult]:
    """Run every PVT point; results come back in grid order regardless of jobs."""
    results: list[PointResult | None] = [None] * len(points)

    def _one(index_point):
        index, point = index_point
        result = run_point(tb, pdk, point, workdir, timeout_s=timeout_s, log_dir=log_dir)
        results[index] = result
        if on_result is not None:
            on_result(result)
        return result

    if jobs <= 1:
        for item in enumerate(points):
            _one(item)
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            list(pool.map(_one, enumerate(points)))

    return [r for r in results if r is not None]
